-- SPC War Room Engine core schema
-- Creates dedicated SPC tables aligned to existing SmartLab domain

-- Measurements captured for SPC (linked to lab_analysis when available)
create table if not exists public.spc_measurements (
  id uuid default uuid_generate_v4() primary key,
  source_analysis_id uuid references public.lab_analysis(id),
  sample_id uuid references public.samples(id),
  parameter_id uuid references public.parameters(id) not null,
  production_lot_id uuid references public.production_lots(id),
  intermediate_lot_id uuid references public.intermediate_lots(id),
  finished_lot_id uuid references public.finished_lots(id),
  product_id uuid references public.products(id),
  line text,
  value numeric not null,
  unit text,
  measured_at timestamp with time zone default timezone('utc'::text, now()) not null,
  source text check (source in ('lab', 'online', 'manual', 'import')) default 'lab',
  created_by uuid references public.profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_spc_measurements_param_time on public.spc_measurements(parameter_id, measured_at);
create index if not exists idx_spc_measurements_lot on public.spc_measurements(production_lot_id, finished_lot_id);

-- Chart configuration
create table if not exists public.spc_charts (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  description text,
  parameter_id uuid references public.parameters(id),
  product_id uuid references public.products(id),
  line text,
  chart_type text check (chart_type in ('I-MR', 'Xbar-R', 'Xbar-S', 'P', 'NP', 'C', 'U')) not null default 'I-MR',
  target numeric,
  lsl numeric,
  usl numeric,
  lcl numeric,
  ucl numeric,
  baseline_window integer default 25,
  recalculation_strategy text default 'rolling',
  ruleset text default 'nelson',
  is_active boolean default true,
  created_by uuid references public.profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_spc_charts_parameter on public.spc_charts(parameter_id);
create index if not exists idx_spc_charts_active on public.spc_charts(is_active);

-- Alerts raised by SPC rules or predictions
create table if not exists public.spc_alerts (
  id uuid default uuid_generate_v4() primary key,
  chart_id uuid references public.spc_charts(id),
  parameter_id uuid references public.parameters(id),
  production_lot_id uuid references public.production_lots(id),
  severity text check (severity in ('info', 'warning', 'critical')) not null default 'warning',
  type text check (type in ('rule_violation', 'out_of_control', 'prediction_risk', 'capability')) not null,
  message text not null,
  status text check (status in ('open', 'acknowledged', 'closed')) not null default 'open',
  triggered_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by uuid references public.profiles(id),
  resolved_at timestamp with time zone,
  resolved_by uuid references public.profiles(id)
);

create index if not exists idx_spc_alerts_status on public.spc_alerts(status, triggered_at);
create index if not exists idx_spc_alerts_parameter on public.spc_alerts(parameter_id);

-- Predictions generated by AI/heuristics
create table if not exists public.spc_predictions (
  id uuid default uuid_generate_v4() primary key,
  chart_id uuid references public.spc_charts(id),
  parameter_id uuid references public.parameters(id),
  production_lot_id uuid references public.production_lots(id),
  horizon_minutes integer not null check (horizon_minutes in (30, 60, 120)),
  risk_score numeric not null check (risk_score >= 0 and risk_score <= 1),
  trend text check (trend in ('improving', 'stable', 'degrading')),
  model_version text default 'heuristic-v1',
  generated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_spc_predictions_param on public.spc_predictions(parameter_id, horizon_minutes);

-- Detailed rule violations (linked to alerts)
create table if not exists public.spc_rules_violations (
  id uuid default uuid_generate_v4() primary key,
  alert_id uuid references public.spc_alerts(id) on delete cascade,
  chart_id uuid references public.spc_charts(id),
  parameter_id uuid references public.parameters(id),
  rule_name text not null,
  point_label text,
  point_value numeric,
  point_timestamp timestamp with time zone,
  sequence_index integer,
  details jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_spc_rules_alert on public.spc_rules_violations(alert_id);

-- ---------------------------------------------------------------------------
-- RLS setup: allow authenticated reads; restrict writes to supervisors/managers/admins
-- Role mapping: supervisor -> qa_supervisor, manager -> plant_manager, technician -> lab_tech, auditor -> auditor_readonly
-- ---------------------------------------------------------------------------

alter table public.spc_measurements enable row level security;
alter table public.spc_charts enable row level security;
alter table public.spc_alerts enable row level security;
alter table public.spc_predictions enable row level security;
alter table public.spc_rules_violations enable row level security;

-- Helper policy check for privileged roles
create or replace view public.v_spc_privileged_users as
select id
from public.profiles
where role in ('admin', 'manager', 'supervisor');

-- READ policies (authenticated)
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'spc_measurements' and policyname = 'spc_measurements_read_authenticated') then
    create policy "spc_measurements_read_authenticated" on public.spc_measurements for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'spc_charts' and policyname = 'spc_charts_read_authenticated') then
    create policy "spc_charts_read_authenticated" on public.spc_charts for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'spc_alerts' and policyname = 'spc_alerts_read_authenticated') then
    create policy "spc_alerts_read_authenticated" on public.spc_alerts for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'spc_predictions' and policyname = 'spc_predictions_read_authenticated') then
    create policy "spc_predictions_read_authenticated" on public.spc_predictions for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'spc_rules_violations' and policyname = 'spc_rules_read_authenticated') then
    create policy "spc_rules_read_authenticated" on public.spc_rules_violations for select to authenticated using (true);
  end if;
end $$;

-- WRITE policies (admins/managers/supervisors)
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'spc_measurements' and policyname = 'spc_measurements_write_privileged') then
    create policy "spc_measurements_write_privileged" on public.spc_measurements
      for insert to authenticated with check (exists (select 1 from public.v_spc_privileged_users p where p.id = auth.uid()));
  end if;
  if not exists (select 1 from pg_policies where tablename = 'spc_charts' and policyname = 'spc_charts_write_privileged') then
    create policy "spc_charts_write_privileged" on public.spc_charts
      for insert to authenticated with check (exists (select 1 from public.v_spc_privileged_users p where p.id = auth.uid()));
  end if;
  if not exists (select 1 from pg_policies where tablename = 'spc_alerts' and policyname = 'spc_alerts_write_privileged') then
    create policy "spc_alerts_write_privileged" on public.spc_alerts
      for insert to authenticated with check (exists (select 1 from public.v_spc_privileged_users p where p.id = auth.uid()));
  end if;
  if not exists (select 1 from pg_policies where tablename = 'spc_predictions' and policyname = 'spc_predictions_write_privileged') then
    create policy "spc_predictions_write_privileged" on public.spc_predictions
      for insert to authenticated with check (exists (select 1 from public.v_spc_privileged_users p where p.id = auth.uid()));
  end if;
  if not exists (select 1 from pg_policies where tablename = 'spc_rules_violations' and policyname = 'spc_rules_write_privileged') then
    create policy "spc_rules_write_privileged" on public.spc_rules_violations
      for insert to authenticated with check (exists (select 1 from public.v_spc_privileged_users p where p.id = auth.uid()));
  end if;
end $$;

-- UPDATE policies (privileged)
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'spc_alerts' and policyname = 'spc_alerts_update_privileged') then
    create policy "spc_alerts_update_privileged" on public.spc_alerts
      for update to authenticated using (exists (select 1 from public.v_spc_privileged_users p where p.id = auth.uid()))
      with check (exists (select 1 from public.v_spc_privileged_users p where p.id = auth.uid()));
  end if;
  if not exists (select 1 from pg_policies where tablename = 'spc_charts' and policyname = 'spc_charts_update_privileged') then
    create policy "spc_charts_update_privileged" on public.spc_charts
      for update to authenticated using (exists (select 1 from public.v_spc_privileged_users p where p.id = auth.uid()))
      with check (exists (select 1 from public.v_spc_privileged_users p where p.id = auth.uid()));
  end if;
end $$;
